[build]
  publish = "public"
  command = "hugo --gc"

[build.environment]
  HUGO_VERSION = "0.73.0"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --buildFuture"

[context.deploy-preview.environment]
  HUGO_ENV = "deploy-preview"

[[redirects]]
  from = "http://blog.shealevy.com/*"
  to = "http://shealevy.com/blog/:splat"
  force = true

[[redirects]]
  from = "https://blog.shealevy.com/*"
  to = "https://shealevy.com/blog/:splat"
  force = true
